{
 "title": "Dashboard SOC Vulnerabilidades Home",
 "tags": [ "Soc" ],
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Filtro", "label": "Filtro de tempo", "query": "6M,1d,2d,5d,15d,30d" },
   {
    "name": "Grupo",
    "query": "{\"find\":\"terms\", \"field\":\"agent.labels.group\", \"query\":\"agent.labels.group:Urbano_Bank\"} "
   },
   {
    "name": "Servidor",
    "query": "{\"find\":\"terms\", \"field\":\"agent.name\", \"query\":\"agent.labels.group:$Grupo\"} "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<style>\n\n body {\n    margin: 0;\n    font-family: Arial, sans-serif;\n}\n\n.custom-header {\n    background-color: #333;\n    color: #fff;\n    padding: 20px;\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n}\n\n.custom-logo img {\n    max-width: 65px;\n}\n.logo-text {\n    font-size: 20px; /* Tamanho do texto */\n    margin-left: 30px; /* Espaçamento entre o texto e o logo */\n}\n\nnav ul {\n    list-style-type: none;\n    margin: 0;\n    padding: 0;\n    display: flex;\n}\n\n.custom-nav-links {\n    display: flex;\n    justify-content: center;\n    align-items: center ;\n}\n\n.custom-nav-links li {\n    margin-right:20px;\n    text-align: center;\n}\n\n.custom-nav-links a {\n    color: #fff;\n    text-decoration: none;\n}\n\n.custom-nav-links a:hover {\n    color: pink;\n}\n\n.custom-dropdown:hover .custom-dropdown-content {\n    display: block;\n}\n\n.custom-dropdown-content {\n    display: none;\n    position: absolute;\n    background-color: #333;\n    min-width: 150px;\n    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);\n}\n\n.custom-dropdown-content li {\n    padding: 10px;\n}\n\n.custom-arrow {\n    border: solid white;\n    border-width: 0 3px 3px 0;\n    display: inline-block;\n    padding: 3px;\n}\n\n.down {\n    transform: rotate(45deg);\n}\n\n@media screen and (max-width: 768px) {\n    .custom-nav-links {\n        display: none;\n        flex-direction: column;\n        background-color: #333;\n        position: absolute;\n        top: 80px;\n        left: 0;\n        width: 100%;\n    }\n    .custom-nav-links li {\n        text-align: center;\n        margin: 0;\n    }\n    .custom-nav-links li a {\n        padding: 10px;\n        display: block;\n        border-bottom: 1px solid #777;\n    }\n    .custom-nav-links li:last-child a {\n        border-bottom: none;\n    }\n    .custom-nav-links.show {\n        display: flex;\n    }\n    .custom-dropdown-content {\n        position: static;\n    }\n    }\n\n@media screen and (max-width: 768px) {\n    .logo-text {\n        display: none; /* Ocultar o texto em dispositivos menores */\n    }\n}\n\n\n  </style>\n\n<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Header Responsivo</title>\n     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" integrity=\"sha384-+ccJqDOB65iT8rOiVYDrC5bM5T9eyGrBfMjQrKDO5wkeDTcg9q7lsTz2tx3bo2R5\" crossorigin=\"anonymous\">\n    <!-- Incluindo Font Awesome -->\n    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" integrity=\"sha384-+ccJqDOB65iT8rOiVYDrC5bM5T9eyGrBfMjQrKDO5wkeDTcg9q7lsTz2tx3bo2R5\" crossorigin=\"anonymous\">\n</head>\n<body>\n    <header class=\"custom-header\">\n        <div class=\"custom-logo\">\n           \n         <a href=\"#\"><img src=\"https://www.lgti.com.br/wp-content/uploads/2023/07/2-2-922x1024.png\" alt=\"Logo\"></a>\n          <span class=\"logo-text\">Home</span>\n        </div>\n        <nav>\n            <ul class=\"custom-nav-links\">\n\n                <li><a href=\"https://portal.cloudash.com.br/d/f599f35b-d207-46f3-a3ea-6397295d4c82/dashboard-soc-vulnerabilidades-home?orgId=87&refresh=5m\"><i class=\"fa fa-home\"></i> Home</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-vulnerabilidades-ativas/dashboard-soc-vulnerabilidades-ativas?orgId=87&var-Filtro=6M&var-Grupo=Urbano_Bank&var-Servidor=ip-10-10-130-6\"><i class=\"fa fa-shield\"></i> Vulnerabilidades Ativas</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-vulnerabilidades-resolvidas/dashboard-soc-vulnerabilidades-resolvidas?orgId=87&var-Filtro=6M&var-Grupo=Urbano_Bank&var-Servidor=ip-10-10-130-6\"><i class=\"fa fa-shield\"></i> Vulnerabilidades Resolvidas</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-fluxo-de-ataque/dashboard-soc-fluxo-de-ataques?orgId=87\"><i class=\"fa fa-sitemap\"></i> Fluxo</a></li>\n               <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-alertas/dashboard-soc-alertas?orgId=87\"><i class=\"fa fa-bullhorn\"></i> Alertas</a></li>\n               <li><a href=\"https://portal.cloudash.com.br/d/a479ec87-ac63-4a9e-9cfe-5795dffbd789/dashboard-soc-relatorio?orgId=87&var-Filtro=6M&var-Grupo=Urbano_Bank&var-Servidor=ip-10-10-130-6\"><i class=\"fa fa-file-text-o\"></i> Relatório</a></li>\n            </ul>\n        </nav>\n    </header>\n    <script src=\"script.js\"></script>\n</body>\n</html>\n<script>\n    const navSlide = () => {\n    const burger = document.querySelector('.burger');\n    const nav = document.querySelector('.custom-nav-links');\n\n    burger.addEventListener('click', () => {\n        nav.classList.toggle('show');\n    });\n}\n\nnavSlide();\n</script>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "7000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Low  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Medium  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Low",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Low  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Medium AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:High  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.labels.group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "7000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Critical  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "High",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:High AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.severity",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Critical AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}