{
 "title": "Dashboard SOC Relatorio",
 "tags": [ "Soc" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filtro", "label": "Filtro de tempo", "query": "6M,1d,2d,5d,15d,30d" },
   {
    "name": "Grupo",
    "query": "{\"find\":\"terms\", \"field\":\"agent.labels.group\", \"query\":\"agent.labels.group:Urbano_Bank\"} "
   },
   {
    "name": "Servidor",
    "query": "{\"find\":\"terms\", \"field\":\"agent.name\", \"query\":\"agent.labels.group:$Grupo\"} "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<style>\n\n body {\n    margin: 0;\n    font-family: Arial, sans-serif;\n}\n\n.custom-header {\n    background-color: #333;\n    color: #fff;\n    padding: 20px;\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n}\n\n.custom-logo img {\n    max-width: 65px;\n}\n.logo-text {\n    font-size: 20px; /* Tamanho do texto */\n    margin-left: 30px; /* Espaçamento entre o texto e o logo */\n}\n\nnav ul {\n    list-style-type: none;\n    margin: 0;\n    padding: 0;\n    display: flex;\n}\n\n.custom-nav-links {\n    display: flex;\n    justify-content: center;\n    align-items: center ;\n}\n\n.custom-nav-links li {\n    margin-right:20px;\n    text-align: center;\n}\n\n.custom-nav-links a {\n    color: #fff;\n    text-decoration: none;\n}\n\n.custom-nav-links a:hover {\n    color: pink;\n}\n\n.custom-dropdown:hover .custom-dropdown-content {\n    display: block;\n}\n\n.custom-dropdown-content {\n    display: none;\n    position: absolute;\n    background-color: #333;\n    min-width: 150px;\n    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);\n}\n\n.custom-dropdown-content li {\n    padding: 10px;\n}\n\n.custom-arrow {\n    border: solid white;\n    border-width: 0 3px 3px 0;\n    display: inline-block;\n    padding: 3px;\n}\n\n.down {\n    transform: rotate(45deg);\n}\n\n@media screen and (max-width: 768px) {\n    .custom-nav-links {\n        display: none;\n        flex-direction: column;\n        background-color: #333;\n        position: absolute;\n        top: 80px;\n        left: 0;\n        width: 100%;\n    }\n    .custom-nav-links li {\n        text-align: center;\n        margin: 0;\n    }\n    .custom-nav-links li a {\n        padding: 10px;\n        display: block;\n        border-bottom: 1px solid #777;\n    }\n    .custom-nav-links li:last-child a {\n        border-bottom: none;\n    }\n    .custom-nav-links.show {\n        display: flex;\n    }\n    .custom-dropdown-content {\n        position: static;\n    }\n    }\n\n@media screen and (max-width: 768px) {\n    .logo-text {\n        display: none; /* Ocultar o texto em dispositivos menores */\n    }\n}\n\n\n  </style>\n\n<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Header Responsivo</title>\n     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" integrity=\"sha384-+ccJqDOB65iT8rOiVYDrC5bM5T9eyGrBfMjQrKDO5wkeDTcg9q7lsTz2tx3bo2R5\" crossorigin=\"anonymous\">\n    <!-- Incluindo Font Awesome -->\n    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" integrity=\"sha384-+ccJqDOB65iT8rOiVYDrC5bM5T9eyGrBfMjQrKDO5wkeDTcg9q7lsTz2tx3bo2R5\" crossorigin=\"anonymous\">\n</head>\n<body>\n    <header class=\"custom-header\">\n        <div class=\"custom-logo\">\n           \n         <a href=\"#\"><img src=\"https://www.lgti.com.br/wp-content/uploads/2023/07/2-2-922x1024.png\" alt=\"Logo\"></a>\n          <span class=\"logo-text\">Relatório</span>\n        </div>\n        <nav>\n            <ul class=\"custom-nav-links\">\n                <li><a href=\"https://portal.cloudash.com.br/d/f599f35b-d207-46f3-a3ea-6397295d4c82/dashboard-soc-vulnerabilidades-home?orgId=87&refresh=5m\"><i class=\"fa fa-home\"></i> Home</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-vulnerabilidades-ativas/dashboard-soc-vulnerabilidades-ativas?orgId=87&var-Filtro=6M&var-Grupo=$Grupo&var-Servidor=$Servidor\"><i class=\"fa fa-shield\"></i> Vulnerabilidades Ativas</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-vulnerabilidades-resolvidas/dashboard-soc-vulnerabilidades-resolvidas?orgId=87&var-Filtro=6M&var-Grupo=$Grupo&Servidor=$Servidor\"><i class=\"fa fa-shield\"></i> Vulnerabilidades Resolvidas</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-fluxo-de-ataque/dashboard-soc-fluxo-de-ataques?orgId=87\"><i class=\"fa fa-sitemap\"></i> Fluxo</a></li>\n               <li><a href=\"https://portal.cloudash.com.br/d/dash-soc-alertas/dashboard-soc-alertas?orgId=87\"><i class=\"fa fa-bullhorn\"></i> Alertas</a></li>\n               <li><a href=\"https://portal.cloudash.com.br/d/a479ec87-ac63-4a9e-9cfe-5795dffbd789/dashboard-soc-relatorio?orgId=87&var-Filtro=6M&var-Grupo=$Grupo&Servidor=$Servidor\"><i class=\"fa fa-file-text-o\"></i> Relatório</a></li>\n            </ul>\n        </nav>\n    </header>\n    <script src=\"script.js\"></script>\n</body>\n</html>\n<script>\n    const navSlide = () => {\n    const burger = document.querySelector('.burger');\n    const nav = document.querySelector('.custom-nav-links');\n\n    burger.addEventListener('click', () => {\n        nav.classList.toggle('show');\n    });\n}\n\nnavSlide();\n</script>"
   }
  },
  { "title": "$Servidor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 10px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">Vulnerabilidades e Alertas</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 7 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 5px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">Ativas</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 7 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 5px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">Resolvidas</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 5px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">Nível de alertas</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.labels.group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Low AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.labels.group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Medium  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.labels.group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "2000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "@timestamp",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:High AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.labels.group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Critical  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "id": "16", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Low AND data.vulnerability.status:Solved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "id": "16", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Medium AND data.vulnerability.status:Solved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "id": "16", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:High AND data.vulnerability.status:Solved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.vulnerability.severity",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "16", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:Critical AND data.vulnerability.status:Solved",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Quantidade de alertas nível",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "rule.level:>=10 AND agent.labels.group:$Grupo AND  agent.name:$Servidor",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.labels.group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.cve",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      },
      {
       "field": "data.vulnerability.status",
       "id": "15",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:*  AND location:vulnerability-detector",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.name",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "15", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND data.vulnerability.severity:* AND data.vulnerability.status:Solved NOT data.vulnerability.severity: Untriaged",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 10px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">Security Configuration Assessment - CIS Benchmark</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.sca.passed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.sca.failed",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.sca.invalid",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "data.sca.score",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data.sca.score",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "@timestamp", "id": "1", "type": "max" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:* AND rule.groups:sca",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CIS Benchmark - Passou",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CIS Benchmark - Falhou",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "agent.labels.group:$Grupo AND agent.name:$Servidor AND rule.groups:sca",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 5px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">MITRE ATT&CKS</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "title": "Top 10 Taticas MITRE ATT&CKS ",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 22, "w": 17, "x": 0, "y": 38 },
   "targets": [
    {
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "rule.mitre.tactic",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "agent.labels.group:$Grupo AND  agent.name:$Servidor",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Top 10 Taticas MITRE ATT&CKS",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 38 },
   "targets": [
    {
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "field": "rule.mitre.tactic",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "agent.labels.group:$Grupo AND  agent.name:$Servidor",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Top 10 Técnicas MITRE ATT&CKS ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 49 },
   "targets": [
    {
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "field": "rule.mitre.technique",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "agent.labels.group:$Grupo AND  agent.name:$Servidor",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "timeField": "@timestamp",
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}