{
 "title": "Dashboard Relatório",
 "tags": [ "Estrategico" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "grupo", "label": "Grupo", "query": "Braspress" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<style>\n\n body {\n    margin: 0;\n    font-family: Arial, sans-serif;\n}\n\n.custom-header {\n    background-color: #333;\n    color: #fff;\n    padding: 20px;\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n}\n\n.custom-logo img {\n    max-width: 65px;\n}\n.logo-text {\n    font-size: 20px; /* Tamanho do texto */\n    margin-left: 30px; /* Espaçamento entre o texto e o logo */\n}\n\nnav ul {\n    list-style-type: none;\n    margin: 0;\n    padding: 0;\n    display: flex;\n}\n\n.custom-nav-links {\n    display: flex;\n    justify-content: center;\n    align-items: center ;\n}\n\n.custom-nav-links li {\n    margin-right:20px;\n    text-align: center;\n}\n\n.custom-nav-links a {\n    color: #fff;\n    text-decoration: none;\n}\n\n.custom-nav-links a:hover {\n    color: pink;\n}\n\n.custom-dropdown:hover .custom-dropdown-content {\n    display: block;\n}\n\n.custom-dropdown-content {\n    display: none;\n    position: absolute;\n    background-color: #333;\n    min-width: 150px;\n    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);\n}\n\n.custom-dropdown-content li {\n    padding: 10px;\n}\n\n.custom-arrow {\n    border: solid white;\n    border-width: 0 3px 3px 0;\n    display: inline-block;\n    padding: 3px;\n}\n\n.down {\n    transform: rotate(45deg);\n}\n\n@media screen and (max-width: 768px) {\n    .custom-nav-links {\n        display: none;\n        flex-direction: column;\n        background-color: #333;\n        position: absolute;\n        top: 80px;\n        left: 0;\n        width: 100%;\n    }\n    .custom-nav-links li {\n        text-align: center;\n        margin: 0;\n    }\n    .custom-nav-links li a {\n        padding: 10px;\n        display: block;\n        border-bottom: 1px solid #777;\n    }\n    .custom-nav-links li:last-child a {\n        border-bottom: none;\n    }\n    .custom-nav-links.show {\n        display: flex;\n    }\n    .custom-dropdown-content {\n        position: static;\n    }\n    }\n\n@media screen and (max-width: 768px) {\n    .logo-text {\n        display: none; /* Ocultar o texto em dispositivos menores */\n    }\n}\n\n\n  </style>\n\n<!DOCTYPE html>\n<html lang=\"en\">\n\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Header Responsivo</title>\n     <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" integrity=\"sha384-+ccJqDOB65iT8rOiVYDrC5bM5T9eyGrBfMjQrKDO5wkeDTcg9q7lsTz2tx3bo2R5\" crossorigin=\"anonymous\">\n    <!-- Incluindo Font Awesome -->\n    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" integrity=\"sha384-+ccJqDOB65iT8rOiVYDrC5bM5T9eyGrBfMjQrKDO5wkeDTcg9q7lsTz2tx3bo2R5\" crossorigin=\"anonymous\">\n</head>\n<body>\n    <header class=\"custom-header\">\n        <div class=\"custom-logo\">\n           \n         <a href=\"#\"><img src=\"\thttps://www.lgti.com.br/wp-content/uploads/2021/10/01_Si%CC%81mbolo_LGTI.png\" alt=\"Logo\"></a>\n          <span class=\"logo-text\">Relatório de Incidentes</span>\n        </div>\n        <nav>\n            <ul class=\"custom-nav-links\">\n                <li><a href=\"https://portal.cloudash.com.br/d/dashboard-ativos/dashboard-ativos?orgId=106&refresh=15m\"><i class=\"fa fa-info-circle\"></i> Informações Ativos</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dashboard-manutencao/dashboard-manutencao?orgId=106&refresh=5m\"><i class=\"fa fa-calendar\"></i> Janelas de Manutenção</a></li>\n                <li><a href=\"https://portal.cloudash.com.br/d/dashboard-relatorio-disponibilidade/dashboard-relatorio-de-disponibilidade?orgId=106&refresh=2h\"><i class=\"fa fa-clock-o\"></i> Relatório Disponibilidade</a></li>\n               \n            </ul>\n        </nav>\n    </header>\n    <script src=\"script.js\"></script>\n</body>\n</html>\n<script>\n    const navSlide = () => {\n    const burger = document.querySelector('.burger');\n    const nav = document.querySelector('.custom-nav-links');\n\n    burger.addEventListener('click', () => {\n        nav.classList.toggle('show');\n    });\n}\n\nnavSlide();\n</script>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"background-color:#333; width: 100%; display: flex; justify-content:  space-around; align-items: center; padding: 10px;border-radius: 4em;\" \">\n  \n  <h1 style=\"margin: 0px; padding:0px; font-size: 24px; color:#ffff;\">${__from:date:DD/MM/YYYY HH:mm:ss} Até ${__to:date:DD/MM/YYYY HH:mm:ss}</h1>\n   \n</div>\n\n\n\n\n"
   }
  },
  {
   "title": "Incidentes por Severidade",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  e.severity,\r\n  hstgrp.name AS grupo,\r\n  CASE\r\n    WHEN e.severity = 0 THEN 'Not classified'\r\n    WHEN e.severity = 1 THEN 'Information'\r\n    WHEN e.severity = 2 THEN 'Warning'\r\n    WHEN e.severity = 3 THEN 'Average'\r\n    WHEN e.severity = 4 THEN 'High'\r\n    WHEN e.severity = 5 THEN 'Disaster'\r\n  END AS severidade,\r\n  e.clock,\r\n  DAYOFWEEK(FROM_UNIXTIME(e.clock)) dia_semana,\r\n  DAYNAME(FROM_UNIXTIME(e.clock)) dia_semana2,\r\n  FROM_UNIXTIME(e.clock) AS datahora,\r\n  DATE_ADD(FROM_UNIXTIME(e.clock), INTERVAL 3 HOUR) AS datahora_ajustada,\r\n  DAY(FROM_UNIXTIME(e.clock)) AS dia,\r\n  MONTH(FROM_UNIXTIME(e.clock)) AS mes,\r\n  YEAR(FROM_UNIXTIME(e.clock)) AS ano,\r\n  HOUR(FROM_UNIXTIME(e.clock)) AS hora,\r\n  MINUTE(FROM_UNIXTIME(e.clock)) AS minuto,\r\n  e.name AS incidente,\r\n  ht.hostid,\r\n  ht.host,\r\n  ht.name AS hostname,\r\n  GROUP_CONCAT(DISTINCT eth.ip SEPARATOR ' | ') AS ip,\r\n  MAX(e.acknowledged) AS acknowledged,\r\n  COUNT(DISTINCT e.eventid) AS qtde_ack,\r\n  CASE\r\n    WHEN MIN(e2.clock) IS NOT NULL THEN 'RESOLVED'\r\n    ELSE 'NOT RESOLVED'\r\n  END AS r_status,\r\n  CASE\r\n    WHEN MIN(e2.clock) IS NOT NULL THEN (MIN(e2.clock) - MIN(e.clock))\r\n    ELSE NULL\r\n  END AS r_duracao_seg,\r\n  MIN(e2.clock) AS r_clock,\r\n  DAYOFWEEK(FROM_UNIXTIME(MIN(e2.clock))) r_dia_semana,\r\n  DAYNAME(FROM_UNIXTIME(MIN(e2.clock))) r_dia_semana2,\r\n  FROM_UNIXTIME(MIN(e2.clock)) AS r_datahora,\r\n  DATE_ADD(FROM_UNIXTIME(MIN(e2.clock)), INTERVAL 3 HOUR) AS datahorar_ajustada,\r\n  DAY(FROM_UNIXTIME(MIN(e2.clock))) AS r_dia,\r\n  MONTH(FROM_UNIXTIME(MIN(e2.clock))) AS r_mes,\r\n  YEAR(FROM_UNIXTIME(MIN(e2.clock))) AS r_ano,\r\n  HOUR(FROM_UNIXTIME(MIN(e2.clock))) AS r_hora,\r\n  MINUTE(FROM_UNIXTIME(MIN(e2.clock))) AS r_minuto\r\nFROM\r\n  events e\r\n  LEFT JOIN event_recovery er1 ON e.eventid = er1.eventid\r\n  INNER JOIN functions f ON e.objectid = f.triggerid\r\n  INNER JOIN items i ON f.itemid = i.itemid\r\n  INNER JOIN hosts ht ON i.hostid = ht.hostid\r\n  LEFT JOIN events AS e2 ON e2.eventid = er1.r_eventid\r\n  JOIN triggers AS t ON e.objectid = t.triggerid\r\n  JOIN hosts_groups ON ht.hostid = hosts_groups.hostid\r\n  JOIN hstgrp ON hosts_groups.groupid = hstgrp.groupid\r\n  LEFT JOIN interface eth ON eth.hostid = ht.hostid\r\nWHERE\r\n  e.source = '0'\r\n  AND e.object = '0'\r\n  AND NOT EXISTS (\r\n    SELECT NULL\r\n    FROM event_suppress es\r\n    WHERE es.eventid = e.eventid\r\n  )\r\n  AND e.value = 1\r\n  AND e.severity IN (4, 5, 6)\r\n  AND hstgrp.name LIKE '${grupo:csv$}'\r\n  AND $__unixEpochFilter(e.clock)\r\nGROUP BY\r\n  e.eventid, ht.hostid, ht.host, ht.name, hstgrp.name\r\n#HAVING\r\n#  r_status = 'NOT RESOLVED'\r\nORDER BY\r\n  MIN(e.clock) ASC;\r\n"
    }
   ]
  },
  {
   "title": "Hosts Reincidentes (Ofensores)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "\r\nSELECT ht.name, COUNT(distinct e.eventid) AS qtde,\r\nhstgrp.name AS grupo\r\nFROM events as e\r\n\tleft JOIN problem as p ON e.eventid = p.eventid\r\n\tleft JOIN triggers ON e.objectid = triggers.triggerid\r\n\tleft JOIN functions ON functions.triggerid = triggers.triggerid\r\n\tleft JOIN items ON items.itemid = functions.itemid\r\n\tleft JOIN hosts ht ON items.hostid = ht.hostid\r\n\tJOIN hosts_groups on ht.hostid = hosts_groups.hostid\r\n  JOIN hstgrp on hosts_groups.groupid = hstgrp.groupid\t\t\r\nWHERE e.source = 0\r\n AND $__unixEpochFilter(e.clock)\r\n AND hstgrp.name like '${grupo:csv}'\r\n AND e.severity in (4,5,6)\r\n\tAND ht.name IS NOT null\r\nGROUP BY ht.name, hstgrp.name\r\nORDER BY qtde desc\r\nlimit 10;\r\n"
    }
   ]
  },
  {
   "title": "Incidentes Reincidentes (Ofensores)",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "\r\nSELECT ht.name, e.name as incidente, COUNT(distinct e.eventid) AS qtde,\r\nhstgrp.name AS grupo\r\nFROM events as e\r\n\tleft JOIN problem as p ON e.eventid = p.eventid\r\n\tleft JOIN triggers ON e.objectid = triggers.triggerid\r\n\tleft JOIN functions ON functions.triggerid = triggers.triggerid\r\n\tleft JOIN items ON items.itemid = functions.itemid\r\n\tleft JOIN hosts ht ON items.hostid = ht.hostid\r\n\tJOIN hosts_groups on ht.hostid = hosts_groups.hostid\r\nJOIN hstgrp on hosts_groups.groupid = hstgrp.groupid\r\nWHERE e.source = 0\r\n\tAnd $__unixEpochFilter(e.clock) \r\n\tAND hstgrp.name like '${grupo:csv}'\r\n\tAND e.severity in (4,5,6)\r\n\tAND ht.name IS NOT null\r\nGROUP BY ht.name, e.name, hstgrp.name\r\nORDER BY qtde desc\r\nlimit 20;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Triggers que alarmaram",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT e.name as incidente, COUNT(distinct e.eventid) AS qtde,\r\nhstgrp.name AS grupo\r\nFROM events as e\r\n\tleft JOIN problem as p ON e.eventid = p.eventid\r\n\tleft JOIN triggers ON e.objectid = triggers.triggerid\r\n\tleft JOIN functions ON functions.triggerid = triggers.triggerid\r\n\tleft JOIN items ON items.itemid = functions.itemid\r\n\tleft JOIN hosts ht ON items.hostid = ht.hostid\r\n\tJOIN hosts_groups on ht.hostid = hosts_groups.hostid\r\n  JOIN hstgrp on hosts_groups.groupid = hstgrp.groupid\t\r\nWHERE e.source = 0\r\n\tAND $__unixEpochFilter(e.clock) \r\n\t AND hstgrp.name like '${grupo:csv}'\r\n\t AND e.severity in (4,5,6)\r\n\tAND ht.host IS NOT null\r\nGROUP BY e.name, hstgrp.name\r\nORDER BY qtde desc\r\nlimit 10;"
    }
   ]
  },
  {
   "title": "Lista de Incidentes Não Resolvidos",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  e.severity,\r\n  hstgrp.name AS grupo,\r\n  CASE\r\n    WHEN e.severity = 0 THEN 'Not classified'\r\n    WHEN e.severity = 1 THEN 'Information'\r\n    WHEN e.severity = 2 THEN 'Warning'\r\n    WHEN e.severity = 3 THEN 'Average'\r\n    WHEN e.severity = 4 THEN 'High'\r\n    WHEN e.severity = 5 THEN 'Disaster'\r\n  END AS severidade,\r\n  e.clock,\r\n  DAYOFWEEK(FROM_UNIXTIME(e.clock)) dia_semana,\r\n  DAYNAME(FROM_UNIXTIME(e.clock)) dia_semana2,\r\n  FROM_UNIXTIME(e.clock) AS datahora,\r\n  DATE_ADD(FROM_UNIXTIME(e.clock), INTERVAL 3 HOUR) AS datahora_ajustada,\r\n  DAY(FROM_UNIXTIME(e.clock)) AS dia,\r\n  MONTH(FROM_UNIXTIME(e.clock)) AS mes,\r\n  YEAR(FROM_UNIXTIME(e.clock)) AS ano,\r\n  HOUR(FROM_UNIXTIME(e.clock)) AS hora,\r\n  MINUTE(FROM_UNIXTIME(e.clock)) AS minuto,\r\n  e.name AS incidente,\r\n  ht.hostid,\r\n  ht.host,\r\n  ht.name AS hostname,\r\n  GROUP_CONCAT(DISTINCT eth.ip SEPARATOR ' | ') AS ip,\r\n  MAX(e.acknowledged) AS acknowledged,\r\n  COUNT(DISTINCT e.eventid) AS qtde_ack,\r\n  CASE\r\n    WHEN MIN(e2.clock) IS NOT NULL THEN 'RESOLVED'\r\n    ELSE 'NOT RESOLVED'\r\n  END AS r_status,\r\n  CASE\r\n    WHEN MIN(e2.clock) IS NOT NULL THEN (MIN(e2.clock) - MIN(e.clock))\r\n    ELSE NULL\r\n  END AS r_duracao_seg,\r\n  MIN(e2.clock) AS r_clock,\r\n  DAYOFWEEK(FROM_UNIXTIME(MIN(e2.clock))) r_dia_semana,\r\n  DAYNAME(FROM_UNIXTIME(MIN(e2.clock))) r_dia_semana2,\r\n  FROM_UNIXTIME(MIN(e2.clock)) AS r_datahora,\r\n  DATE_ADD(FROM_UNIXTIME(MIN(e2.clock)), INTERVAL 3 HOUR) AS datahorar_ajustada,\r\n  DAY(FROM_UNIXTIME(MIN(e2.clock))) AS r_dia,\r\n  MONTH(FROM_UNIXTIME(MIN(e2.clock))) AS r_mes,\r\n  YEAR(FROM_UNIXTIME(MIN(e2.clock))) AS r_ano,\r\n  HOUR(FROM_UNIXTIME(MIN(e2.clock))) AS r_hora,\r\n  MINUTE(FROM_UNIXTIME(MIN(e2.clock))) AS r_minuto\r\nFROM\r\n  events e\r\n  LEFT JOIN event_recovery er1 ON e.eventid = er1.eventid\r\n  INNER JOIN functions f ON e.objectid = f.triggerid\r\n  INNER JOIN items i ON f.itemid = i.itemid\r\n  INNER JOIN hosts ht ON i.hostid = ht.hostid\r\n  LEFT JOIN events AS e2 ON e2.eventid = er1.r_eventid\r\n  JOIN triggers AS t ON e.objectid = t.triggerid\r\n  JOIN hosts_groups ON ht.hostid = hosts_groups.hostid\r\n  JOIN hstgrp ON hosts_groups.groupid = hstgrp.groupid\r\n  LEFT JOIN interface eth ON eth.hostid = ht.hostid\r\nWHERE\r\n  e.source = '0'\r\n  AND e.object = '0'\r\n  AND NOT EXISTS (\r\n    SELECT NULL\r\n    FROM event_suppress es\r\n    WHERE es.eventid = e.eventid\r\n  )\r\n  AND e.value = 1\r\n  AND e.severity IN (4, 5, 6)\r\n  AND hstgrp.name LIKE '${grupo:csv$}'\r\n  AND $__unixEpochFilter(e.clock)\r\nGROUP BY\r\n  e.eventid, ht.hostid, ht.host, ht.name, hstgrp.name\r\nHAVING\r\n  r_status = 'NOT RESOLVED'\r\nORDER BY\r\n  MIN(e.clock) ASC;\r\n"
    }
   ]
  },
  {
   "title": "Lista de Incidentes Resolvidos",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\r\n  e.severity,\r\n  hstgrp.name AS grupo,\r\n  CASE\r\n    WHEN e.severity = 0 THEN 'Not classified'\r\n    WHEN e.severity = 1 THEN 'Information'\r\n    WHEN e.severity = 2 THEN 'Warning'\r\n    WHEN e.severity = 3 THEN 'Average'\r\n    WHEN e.severity = 4 THEN 'High'\r\n    WHEN e.severity = 5 THEN 'Disaster'\r\n  END AS severidade,\r\n  e.clock,\r\n  DAYOFWEEK(FROM_UNIXTIME(e.clock)) dia_semana,\r\n  DAYNAME(FROM_UNIXTIME(e.clock)) dia_semana2,\r\n  FROM_UNIXTIME(e.clock) AS datahora,\r\n  DATE_ADD(FROM_UNIXTIME(e.clock), INTERVAL 3 HOUR) AS datahora_ajustada,\r\n  DAY(FROM_UNIXTIME(e.clock)) AS dia,\r\n  MONTH(FROM_UNIXTIME(e.clock)) AS mes,\r\n  YEAR(FROM_UNIXTIME(e.clock)) AS ano,\r\n  HOUR(FROM_UNIXTIME(e.clock)) AS hora,\r\n  MINUTE(FROM_UNIXTIME(e.clock)) AS minuto,\r\n  e.name AS incidente,\r\n  ht.hostid,\r\n  ht.host,\r\n  ht.name AS hostname,\r\n  GROUP_CONCAT(DISTINCT eth.ip SEPARATOR ' | ') AS ip,\r\n  MAX(e.acknowledged) AS acknowledged,\r\n  COUNT(DISTINCT e.eventid) AS qtde_ack,\r\n  CASE\r\n    WHEN MIN(e2.clock) IS NOT NULL THEN 'RESOLVED'\r\n    ELSE 'NOT RESOLVED'\r\n  END AS r_status,\r\n  CASE\r\n    WHEN MIN(e2.clock) IS NOT NULL THEN (MIN(e2.clock) - MIN(e.clock))\r\n    ELSE NULL\r\n  END AS r_duracao_seg,\r\n  MIN(e2.clock) AS r_clock,\r\n  DAYOFWEEK(FROM_UNIXTIME(MIN(e2.clock))) r_dia_semana,\r\n  DAYNAME(FROM_UNIXTIME(MIN(e2.clock))) r_dia_semana2,\r\n  FROM_UNIXTIME(MIN(e2.clock)) AS r_datahora,\r\n  DATE_ADD(FROM_UNIXTIME(MIN(e2.clock)), INTERVAL 3 HOUR) AS datahorar_ajustada,\r\n  DAY(FROM_UNIXTIME(MIN(e2.clock))) AS r_dia,\r\n  MONTH(FROM_UNIXTIME(MIN(e2.clock))) AS r_mes,\r\n  YEAR(FROM_UNIXTIME(MIN(e2.clock))) AS r_ano,\r\n  HOUR(FROM_UNIXTIME(MIN(e2.clock))) AS r_hora,\r\n  MINUTE(FROM_UNIXTIME(MIN(e2.clock))) AS r_minuto\r\nFROM\r\n  events e\r\n  LEFT JOIN event_recovery er1 ON e.eventid = er1.eventid\r\n  INNER JOIN functions f ON e.objectid = f.triggerid\r\n  INNER JOIN items i ON f.itemid = i.itemid\r\n  INNER JOIN hosts ht ON i.hostid = ht.hostid\r\n  LEFT JOIN events AS e2 ON e2.eventid = er1.r_eventid\r\n  JOIN triggers AS t ON e.objectid = t.triggerid\r\n  JOIN hosts_groups ON ht.hostid = hosts_groups.hostid\r\n  JOIN hstgrp ON hosts_groups.groupid = hstgrp.groupid\r\n  LEFT JOIN interface eth ON eth.hostid = ht.hostid\r\nWHERE\r\n  e.source = '0'\r\n  AND e.object = '0'\r\n  AND NOT EXISTS (\r\n    SELECT NULL\r\n    FROM event_suppress es\r\n    WHERE es.eventid = e.eventid\r\n  )\r\n  AND e.value = 1\r\n  AND e.severity IN (4, 5, 6)\r\n  AND hstgrp.name LIKE '${grupo:csv$}'\r\n  AND $__unixEpochFilter(e.clock)\r\nGROUP BY\r\n  e.eventid, ht.hostid, ht.host, ht.name, hstgrp.name\r\nHAVING\r\n  r_status = 'RESOLVED'\r\nORDER BY\r\n  MIN(e.clock) ASC;\r\n"
    }
   ]
  }
 ]
}